name: Continuous Integrations
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  create-envfile:
    runs-on: ubuntu-latest
    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DEBUG: True
          envkey_ALLOWED_HOSTS: 127.0.0.1,localhost
          file_name: .env

  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
    - name: Check Code Coverage
      run: |
        coverage run manage.py test
    - name: Checkout Coverage Report
      run: |
        bash <(curl -s https://codecov.io/bash)
